package com.blackink.app.presentation.screens.invoice

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.blackink.app.domain.model.Sale
import com.blackink.app.domain.util.Money
import com.blackink.app.presentation.components.FlipCard
import com.blackink.app.presentation.components.FlipTopBar
import com.blackink.app.presentation.components.PrimaryButton
import com.blackink.app.presentation.components.ScreenScaffold
import com.blackink.app.presentation.rememberViewModel
import com.blackink.app.presentation.theme.FlipTheme

@Composable
fun InvoiceScreen(sale: Sale, onBack: () -> Unit) {
    val colors = FlipTheme.colors
    val vm = rememberViewModel<InvoiceViewModel>()
    val profile by vm.profile.collectAsState()
    val exportPdf = rememberInvoicePdfExporter()

    val invoiceNo = sale.id.takeLast(6).uppercase()
    val business = profile.businessName.ifBlank { "BlackInk" }
    val amount = Money.format(sale.revenueCents, profile.currency)
    val billedDetails = listOfNotNull(
        sale.customerEmail.takeIf { it.isNotBlank() },
        sale.customerPhone.takeIf { it.isNotBlank() },
        sale.customerAddress.takeIf { it.isNotBlank() },
    )

    val doc = InvoiceDocument(
        businessName = business,
        ownerName = profile.ownerName,
        invoiceNumber = invoiceNo,
        date = sale.soldDate,
        billedToName = sale.customerName.ifBlank { "Customer not provided" },
        billedToDetails = billedDetails,
        items = listOf(
            InvoiceLineItem(
                description = sale.model,
                meta = sale.channel?.label.orEmpty(),
                amount = amount,
            ),
        ),
        subTotal = amount,
        total = amount,
        footerNote = "Payment received in full. Generated by $business.",
    )

    ScreenScaffold {
        FlipTopBar(title = "Invoice", onBack = onBack)
        Column(Modifier.weight(1f).verticalScroll(rememberScrollState()).padding(20.dp)) {
            Text("INVOICE", style = FlipTheme.typography.displayM, color = colors.textDefault)
            Text("#$invoiceNo · ${sale.soldDate}", style = FlipTheme.typography.bodyM, color = colors.textWeaker)
            Spacer(Modifier.padding(8.dp))

            FlipCard(Modifier.fillMaxWidth()) {
                Text("BILLED TO", style = FlipTheme.typography.caption, color = colors.textWeakest)
                Text(doc.billedToName, style = FlipTheme.typography.headingM, color = colors.textDefault)
                billedDetails.forEach { Text(it, style = FlipTheme.typography.bodyM, color = colors.textWeaker) }
            }
            Spacer(Modifier.padding(6.dp))

            FlipCard(Modifier.fillMaxWidth()) {
                Text("PAY TO", style = FlipTheme.typography.caption, color = colors.textWeakest)
                Text(business, style = FlipTheme.typography.headingM, color = colors.textDefault)
                if (profile.ownerName.isNotBlank()) {
                    Text(profile.ownerName, style = FlipTheme.typography.bodyM, color = colors.textWeaker)
                }
            }
            Spacer(Modifier.padding(6.dp))

            FlipCard(Modifier.fillMaxWidth()) {
                doc.items.forEach { item ->
                    invoiceRow(item.description, item.amount)
                }
                invoiceRow("Total", doc.total, emphasize = true)
            }
            Spacer(Modifier.padding(8.dp))
        }
        Column(Modifier.padding(20.dp)) {
            PrimaryButton("Share invoice (PDF)", { exportPdf(doc) })
        }
    }
}

@Composable
private fun invoiceRow(label: String, value: String, emphasize: Boolean = false) {
    Row(Modifier.fillMaxWidth().padding(vertical = 8.dp), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(
            label,
            style = if (emphasize) FlipTheme.typography.headingS else FlipTheme.typography.bodyM,
            color = if (emphasize) FlipTheme.colors.textDefault else FlipTheme.colors.textWeaker,
        )
        Text(value, style = FlipTheme.typography.headingS, color = FlipTheme.colors.textDefault)
    }
}
